c:\cvision\cformat -l#left -lop+ -ls3 -lt- -lp3,3 -lalign -lindent DLLSTACK.C -o.\vis\DLLSTACK.C

c:\cvision\cformat -l#left -lop+ -ls3 -lt- -lp3,3 -lalign -lindent MAINWIND.CPP -o.\vis\MAINWIND.CPP

c:\cvision\cformat -l#left -lop+ -ls3 -lt- -lp3,3 -lalign -lindent DDEWIND.CPP -o.\vis\DDEWIND.CPP

c:\cvision\cformat -l#left -lop+ -ls3 -lt- -lp3,3 -lalign -lindent DLLWIND.CPP -o.\vis\DLLWIND.CPP

c:\cvision\cformat -l#left -lop+ -ls3 -lt- -lp3,3 -lalign -lindent ASSEMBLY.CPP -o.\vis\ASSEMBLY.CPP

c:\cvision\cformat -l#left -lop+ -ls3 -lt- -lp3,3 -lalign -lindent VECTOR.CPP -o.\vis\VECTOR.CPP

c:\cvision\cformat -l#left -lop+ -ls3 -lt- -lp3,3 -lalign -lindent THREED.CPP -o.\vis\THREED.CPP

c:\cvision\cformat -l#left -lop+ -ls3 -lt- -lp3,3 -lalign -lindent MYFILEWN.CPP -o.\vis\MYFILEWN.CPP

c:\cvision\cformat -l#left -lop+ -ls3 -lt- -lp3,3 -lalign -lindent MYFILEED.CPP -o.\vis\MYFILEED.CPP

c:\cvision\cformat -l#left -lop+ -ls3 -lt- -lp3,3 -lalign -lindent NETWIND.CPP -o.\vis\NETWIND.CPP

c:\cvision\cformat -l#left -lop+ -ls3 -lt- -lp3,3 -lalign -lindent GRAPHWIN.CPP -o.\vis\GRAPHWIN.CPP

c:\cvision\cformat -l#left -lop+ -ls3 -lt- -lp3,3 -lalign -lindent FILESWND.CPP -o.\vis\FILESWND.CPP

c:\cvision\cformat -l#left -lop+ -ls3 -lt- -lp3,3 -lalign -lindent DLGWIND.CPP -o.\vis\DLGWIND.CPP

c:\cvision\cformat -l#left -lop+ -ls3 -lt- -lp3,3 -lalign -lindent EVAL.CPP -o.\vis\EVAL.CPP

c:\cvision\cformat -l#left -lop+ -ls3 -lt- -lp3,3 -lalign -lindent DIB.CPP -o.\vis\DIB.CPP

c:\cvision\cformat -l#left -lop+ -ls3 -lt- -lp3,3 -lalign -lindent FILEWND.CPP -o.\vis\FILEWND.CPP

c:\cvision\cformat -l#left -lop+ -ls3 -lt- -lp3,3 -lalign -lindent LIBLOC.CPP -o.\vis\LIBLOC.CPP

c:\cvision\cformat -l#left -lop+ -ls3 -lt- -lp3,3 -lalign -lindent UNIX.CPP -o.\vis\UNIX.CPP

c:\cvision\cformat -l#left -lop+ -ls3 -lt- -lp3,3 -lalign -lindent ERROR.CPP -o.\vis\ERROR.CPP

c:\cvision\cformat -l#left -lop+ -ls3 -lt- -lp3,3 -lalign -lindent IBMTERM.CPP -o.\vis\IBMTERM.CPP

c:\cvision\cformat -l#left -lop+ -ls3 -lt- -lp3,3 -lalign -lindent PAREN.CPP -o.\vis\PAREN.CPP

c:\cvision\cformat -l#left -lop+ -ls3 -lt- -lp3,3 -lalign -lindent TERM.CPP -o.\vis\TERM.CPP

c:\cvision\cformat -l#left -lop+ -ls3 -lt- -lp3,3 -lalign -lindent MEM.CPP -o.\vis\MEM.CPP

c:\cvision\cformat -l#left -lop+ -ls3 -lt- -lp3,3 -lalign -lindent WRKSP.CPP -o.\vis\WRKSP.CPP

c:\cvision\cformat -l#left -lop+ -ls3 -lt- -lp3,3 -lalign -lindent INTERN.CPP -o.\vis\INTERN.CPP

c:\cvision\cformat -l#left -lop+ -ls3 -lt- -lp3,3 -lalign -lindent COMS.CPP -o.\vis\COMS.CPP

c:\cvision\cformat -l#left -lop+ -ls3 -lt- -lp3,3 -lalign -lindent LOGODATA.CPP -o.\vis\LOGODATA.CPP

c:\cvision\cformat -l#left -lop+ -ls3 -lt- -lp3,3 -lalign -lindent LISTS.CPP -o.\vis\LISTS.CPP

c:\cvision\cformat -l#left -lop+ -ls3 -lt- -lp3,3 -lalign -lindent MAIN.CPP -o.\vis\MAIN.CPP

c:\cvision\cformat -l#left -lop+ -ls3 -lt- -lp3,3 -lalign -lindent COLORDLG.CPP -o.\vis\COLORDLG.CPP

c:\cvision\cformat -l#left -lop+ -ls3 -lt- -lp3,3 -lalign -lindent SIZEDLG.CPP -o.\vis\SIZEDLG.CPP

c:\cvision\cformat -l#left -lop+ -ls3 -lt- -lp3,3 -lalign -lindent CMDWIND.CPP -o.\vis\CMDWIND.CPP

c:\cvision\cformat -l#left -lop+ -ls3 -lt- -lp3,3 -lalign -lindent INIT.CPP -o.\vis\INIT.CPP

c:\cvision\cformat -l#left -lop+ -ls3 -lt- -lp3,3 -lalign -lindent MATH.CPP -o.\vis\MATH.CPP

c:\cvision\cformat -l#left -lop+ -ls3 -lt- -lp3,3 -lalign -lindent FILES.CPP -o.\vis\FILES.CPP

c:\cvision\cformat -l#left -lop+ -ls3 -lt- -lp3,3 -lalign -lindent GRAPHICS.CPP -o.\vis\GRAPHICS.CPP

c:\cvision\cformat -l#left -lop+ -ls3 -lt- -lp3,3 -lalign -lindent PRINT.CPP -o.\vis\PRINT.CPP

c:\cvision\cformat -l#left -lop+ -ls3 -lt- -lp3,3 -lalign -lindent STATWIND.CPP -o.\vis\STATWIND.CPP

c:\cvision\cformat -l#left -lop+ -ls3 -lt- -lp3,3 -lalign -lindent PARSE.CPP -o.\vis\PARSE.CPP

c:\cvision\cformat -l#left -lop+ -ls3 -lt- -lp3,3 -lalign -lindent AREAWIND.CPP -o.\vis\AREAWIND.CPP

c:\cvision\cformat -l#left -lop+ -ls3 -lt- -lp3,3 -lalign -lindent MMWIND.CPP -o.\vis\MMWIND.CPP

c:\cvision\cformat -l#left -lop+ -ls3 -lt- -lp3,3 -lalign -lindent EDITWND.CPP -o.\vis\EDITWND.CPP

c:\cvision\cformat -l#left -lop+ -ls3 -lt- -lp3,3 -lalign -lindent DEVWIND.CPP -o.\vis\DEVWIND.CPP

c:\cvision\cformat -l#left -lop+ -ls3 -lt- -lp3,3 -lalign -lindent EDITWND.H -o.\vis\EDITWND.H

c:\cvision\cformat -l#left -lop+ -ls3 -lt- -lp3,3 -lalign -lindent VECTOR.H -o.\vis\VECTOR.H

c:\cvision\cformat -l#left -lop+ -ls3 -lt- -lp3,3 -lalign -lindent THREED.H -o.\vis\THREED.H

c:\cvision\cformat -l#left -lop+ -ls3 -lt- -lp3,3 -lalign -lindent FILEWND.H -o.\vis\FILEWND.H

c:\cvision\cformat -l#left -lop+ -ls3 -lt- -lp3,3 -lalign -lindent ALLWIND.H -o.\vis\ALLWIND.H

c:\cvision\cformat -l#left -lop+ -ls3 -lt- -lp3,3 -lalign -lindent GLOBALS.H -o.\vis\GLOBALS.H

c:\cvision\cformat -l#left -lop+ -ls3 -lt- -lp3,3 -lalign -lindent CLASS.H -o.\vis\CLASS.H

c:\cvision\cformat -l#left -lop+ -ls3 -lt- -lp3,3 -lalign -lindent IBMTERM.H -o.\vis\IBMTERM.H

c:\cvision\cformat -l#left -lop+ -ls3 -lt- -lp3,3 -lalign -lindent DIB.H -o.\vis\DIB.H

c:\cvision\cformat -l#left -lop+ -ls3 -lt- -lp3,3 -lalign -lindent LOGO.H -o.\vis\LOGO.H

c:\cvision\cformat -l#left -lop+ -ls3 -lt- -lp3,3 -lalign -lindent FUNC.H -o.\vis\FUNC.H

c:\cvision\cformat -l#left -lop+ -ls3 -lt- -lp3,3 -lalign -lindent OWLRC.H -o.\vis\OWLRC.H

c:\cvision\cformat -l#left -lop+ -ls3 -lt- -lp3,3 -lalign -lindent COLORDLG.H -o.\vis\COLORDLG.H

c:\cvision\cformat -l#left -lop+ -ls3 -lt- -lp3,3 -lalign -lindent LOGOX.H -o.\vis\LOGOX.H

c:\cvision\cformat -l#left -lop+ -ls3 -lt- -lp3,3 -lalign -lindent LOGORC.H -o.\vis\LOGORC.H

c:\cvision\cformat -l#left -lop+ -ls3 -lt- -lp3,3 -lalign -lindent CTL3D.H -o.\vis\CTL3D.H

